id = "kalcite"
name = "Kalcite"
version = "0.3.0"
schema_version = 1
authors = ["DrapNard <drapnard@proton.me>"]
description = "Kalcite language support with Tree-sitter and kalcite-lsp"
repository = "https://github.com/Kalcite-Engine/zed-kalcite"

[grammars.kalcite]
repository = "https://github.com/Kalcite-Engine/tree-sitter-kalcite"
rev = "76141475cab1bd998a63ed3b21cb8c3e9f31330b"

[language_servers.kalcite-lsp]
name = "Kalcite Language Server"
languages = ["Kalcite"]
