id = "kalcite"
name = "Kalcite"
version = "0.3.0"
schema_version = 1
authors = ["DrapNard <drapnard@proton.me>"]
description = "Kalcite language support with Tree-sitter and kalcite-lsp"
repository = "https://github.com/Kalcite-Engine/zed-kalcite"

[grammars.kalcite]
repository = "https://github.com/Kalcite-Engine/tree-sitter-kalcite"
rev = "289af1eae89bc4fb9e326c79e7ccd3613505957c"

[language_servers.kalcite-lsp]
name = "Kalcite Language Server"
languages = ["Kalcite"]
