id = "kalcite"
name = "Kalcite"
version = "0.3.3"
schema_version = 1
authors = ["DrapNard <drapnard@proton.me>"]
description = "Kalcite language support with Tree-sitter and kalcite-lsp"
repository = "https://github.com/Kalcite-Engine/zed-kalcite"

[grammars.kalcite]
repository = "https://github.com/Kalcite-Engine/tree-sitter-kalcite"
rev = "82229e686b941f35be6bcc1aad420bef42b7e91e"

[language_servers.kalcite-lsp]
name = "Kalcite Language Server"
languages = ["Kalcite"]
